networks:
  jekyll:
    external: false

services:
  garden:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jekyll
    restart: no
    networks:
      - jekyll
    volumes:
      - ./_posts:/usr/src/app/_posts
      - ./_notes:/usr/src/app/_notes
      - ./assets:/usr/src/app/assets
      - ./pages:/usr/src/app/pages
      - ./_data:/usr/src/app/_data
    ports:
      - "4000:4000"

